apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastest-jenkins-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
status: {}
