kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastest-data-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ~/.elastestK8s
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastest-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
