version: '3'
services:
        entrypoint: /run.sh
        expose:
            - 8091
        ports:
            - 37006:8091
        volumes:
            - /test-results:/test-results
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - elastest

    etm-beats:
        container_name: beats
        image: elastest/etm-dockbeat
        environment:
            - LOGSTASHHOST=logstash
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - etm-logstash
        networks:
            - elastest
        
    etm-logstash:        
        container_name: logstash
        image: elastest/etm-logstash
        ports:
            - 5002:5002
            - 5000:5000
            - 5001:5001
            - 5044:5044
        depends_on:
            - etm-rabbitmq
            - edm-elasticsearch
        environment:
            - ELASTICHOST=edm-elasticsearch
            - RABBITHOST=etm-rabbitmq
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
                                  
    etm-rabbitmq:
        container_name: etm-rabbitmq
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        ports:
            - 15672:15672
            - 5672:5672
            - 15671:15671
            - 25672:25672
            - 61613:61613
        networks:
            - elastest

    edm-mysql:
        container_name: mysql-db
        image: mysql
        expose:
            - 3306
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=elastest
            - MYSQL_USER=elastest
            - MYSQL_PASSWORD=elastest
            - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
        volumes:
            - mysql:/var/lib/mysql
        networks:
   
    edm-elasticsearch:
        container_name: elasticsearch
        image: elastest/etm-elasticsearch
        ports:
            - 9200:9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - elastest 

    eus:
        container_name: elastest-eus
        image: elastest/eus
        environment:
            - USE_TORM=true
        expose:
            - 8040
        ports:
            - 8040:8040
        networks:
            - elastest
     
volumes:
    beats-data:
      driver: local
networks:
    elastest:
      driver: bridge
