version: '2.1'
services:
    mysql:
        image: mysql
        expose:
            - 3306
        environment:
            - MYSQL_DATABASE=elastest
	    - MYSQL_USER= elastest
	    - MYSQL_PASSWORD= elastest
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - elastest
            
    beats:
        image: elastest/etm-dockbeat
        environment:
            - LOGSTASHHOST=logstash
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - logstash
        networks:
            - elastest
        
    logstash:        
        image: elastest/etm-logstash
        expose:
            - 5002
            - 5000
            - 5001
            - 5044
        depends_on:
            - rabbit-MQ
            - elasticsearch
        environment:
            - ELASTICHOST=elasticsearch
            - RABBITHOST=rabbit-MQ
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
               
    elasticsearch:
        image: elastest/etm-elasticsearch
        expose:
            - 9200
        environment:
            - xpack.security.enabled=false
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - elastest
                   
    rabbit-MQ:
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        expose:
            - 15672
            - 5672
            - 15671
            - 25672
            - 61613
        networks:
            - elastest

volumes:
    elasticsearch-data:
      driver: local
    beats-data:
      driver: local
    mysql:
      driver: local
networks:
    elastest:
      driver: bridge
