version: '3'
services:
    etm-beats:
        image: elastest/etm-dockbeat
        environment:
            - LOGSTASHHOST=etm-logstash
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - etm-logstash
        networks:
            - elastest
        
    etm-logstash:        
        image: elastest/etm-logstash
        expose:
            - 5002
            - 5000
            - 5001
            - 5044
        depends_on:
            - etm-rabbitmq
            - edm-elasticsearch
        environment:
            - ELASTICHOST=edm-elasticsearch
            - RABBITHOST=etm-rabbitmq
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
                                  
    etm-rabbitmq:
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        expose:
            - 15672
            - 5672
            - 15671
            - 25672
            - 61613
        networks:
            - elastest

    edm-mysql:
        image: mysql
        expose:
            - 3306
        environment:
            - MYSQL_DATABASE=elastest
            - MYSQL_USER=elastest
            - MYSQL_PASSWORD=elastest
            - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
        volumes:
            - edm-mysql:/var/lib/mysql
        networks:
            - elastest

    edm-elasticsearch:
        image: elastest/etm-elasticsearch
        expose:
            - 9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
        networks:
            - elastest 

    eus:
        image: elastest/eus
        environment:
            - USE_TORM=true
        expose:
            - 8040
        networks:
            - elastest
     
volumes:
    elasticsearch-data:
      driver: local
    beats-data:
      driver: local
    edm-mysql:
      driver: local
networks:
    elastest:
      driver: bridge
