version: '2.1'
services:
  ems:
    depends_on:
    - elasticsearch
    image: elastest/ems
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    environment:
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    networks:
    - elastest_elastest
networks:
  elastest_elastest:
    driver: bridge