node('TESTDOCKER'){
    
    stage "CI Container setup"

        echo("the node is up")
        def mycontainer = docker.image('elastest/ci-docker-compose-siblings:node7-npm4')
        mycontainer.pull() // make sure we have the latest available from Docker Hub
        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v ${WORKSPACE}:/home/jenkins/.m2 -v /home/ubuntu/.gnupg:/home/jenkins/.gnupg") {
            
        git 'https://github.com/elastest/elastest-torm.git'

        stage "Test and deploy epm-client"
            echo ("Test and deploy epm-client")
            withMaven(maven: 'mvn3.3.9', mavenSettingsConfig: '0e7fd7e6-77b0-4ea2-b808-e8164667a6eb') {
                sh 'cd ./epm-client; mvn deploy -Djenkins=true;'
            }    
}

