version: '3'
services:
    etm-proxy:
        image: elastest/etm-proxy
        expose:
            - 80
            - 443
        ports:
            - 37000:80
            - 37443:443
        depends_on:
            - etm
        networks:
            - elastest
        environment:
            - LOCATION_RULES=nginx-base-location.conf
            - ET_SECURITY=false
            - ET_USER=none
            - ET_PASS=none
networks:
    elastest:
      driver: bridge
