version: '3'
services:        
    etm-jenkins:
      image: 'elastest/etm-jenkins:1.0.3'
      expose:
            - 8080
      environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            - INTEGRATED_JENKINS=true
            - JENKINS_LOCATION=none
            - ET_USER=none
            - ET_PASS=none
            - ET_ETM_VIEW_ONLY=false
      networks:
             - elastest
      volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${ET_DATA_IN_HOST}/jenkins_home:/var/jenkins_home
      logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
networks:
    elastest:
      driver: bridge
