version: '3'
services:        
    etm-jenkins:
      image: 'elastest/etm-jenkins:latest'
      expose:
            - 8080
      environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            - INTEGRATED_JENKINS=true
      networks:
             - elastest
      volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /shared-data/jenkins_home:/var/jenkins_home
networks:
    elastest:
      driver: bridge
