version: '3'
services:        
    etm-logstash:        
        image: elastest/etm-logstash
        expose:
            - 5002
            - 5000
            - 5037
            - 5003
            - 5044
        depends_on:
            - etm-rabbitmq
            - edm-elasticsearch
        environment:
            - ELASTICHOST=edm-elasticsearch
            - RABBITHOST=etm-rabbitmq
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
                                  
    etm-rabbitmq:
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        expose:
            - 15672
            - 5672
            - 15671
            - 25672
            - 61613
        networks:
            - elastest

    edm-mysql:
        image: elastest/edm-mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "elastest"
            MYSQL_USER: elastest
            MYSQL_PASSWORD: elastest
        expose:
            - 3306
        volumes:
            - edm-mysql:/var/lib/mysql
            - ./resources/mysql/config:/etc/mysql/conf.d
        networks:
            - elastest

    edm-elasticsearch:
        image: elastest/etm-elasticsearch
        expose:
            - 9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.security.enabled=false
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - ES_JAVA_OPTS=-Xmx3g -Xms3g
        networks:
            - elastest 

    esm:
      image: elastest/esm
      hostname: esm
      volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
      environment:
            - ESM_PORT=37005
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
            - ET_EDM_MYSQL_HOST=edm-mysql
            - ET_EDM_MYSQL_PORT=3306
            - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:37003/
            - ET_EPM_API=http://epm:37002/
            - ET_ETM_API=http://etm:37006/
            - ET_ESM_API=http://esm:37005/
            - ET_EIM_API=http://eim:37004/
            - ET_ETM_LSBEATS_HOST=etm-logstash
            - ET_ETM_LSBEATS_PORT=5044
            - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
            - ET_ETM_RABBIT_HOST=etm-rabbitmq
            - ET_ETM_RABBIT_PORT=5672
            - ET_EMP_API=http://eim:37001/
            - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
            - ET_EMP_INFLUXDB_HOST=emp-influxdb
            - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
      expose:
            - 37005
      networks:
            - elastest

volumes:
    elasticsearch-data:
      driver: local
    edm-mysql:
      driver: local
networks:
    elastest:
      driver: bridge
