version: '3'
services:
    edm-mysql:
        image: elastest/edm-mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "elastest"
            MYSQL_USER: elastest
            MYSQL_PASSWORD: elastest
        expose:
            - 3306
        volumes:
            - edm-mysql:/var/lib/mysql
            - ./resources/mysql/config:/etc/mysql/conf.d
        networks:
            - elastest

    etm-filebeat:
        image: elastest/etm-filebeat:latest
        environment:
            - ET_MON_LSBEATS_HOST=etm
        networks:
            - elastest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers

    esm:
      image: elastest/esm:latest
      hostname: esm
      volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
      environment:
            - ESM_PORT=37005
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19998/
            - ET_EDM_MYSQL_HOST=edm-mysql
            - ET_EDM_MYSQL_PORT=3306
            - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:8080/
            - ET_EPM_API=http://epm:8180/
            - ET_ETM_API=http://etm:8091/
            - ET_ESM_API=http://esm:37005/
            - ET_EIM_API=http://eim:8080/
            - ET_ETM_LSBEATS_HOST=etm
            - ET_ETM_LSBEATS_PORT=5044
            - ET_ETM_LSHTTP_API=http://etm:5002/
            - ET_ETM_RABBIT_HOST=etm
            - ET_ETM_RABBIT_PORT=5672
            - ET_EMP_API=http://emp:9000/
            - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
            - ET_EMP_INFLUXDB_HOST=emp-influxdb
            - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
      expose:
            - 37005
      networks:
            - elastest

volumes:
    edm-mysql:
      driver: local
networks:
    elastest:
      driver: bridge
