version: '3'
services:
    edm-mysql:
        image: elastest/edm-mysql:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "elastest"
            MYSQL_USER: elastest
            MYSQL_PASSWORD: elastest
        expose:
            - 3306
        volumes:
            - edm-mysql:/var/lib/mysql
            - ./resources/mysql/config:/etc/mysql/conf.d
        networks:
            - elastest

    etm-filebeat:
        image: elastest/etm-filebeat:latest
        environment:
            - ET_MON_LSBEATS_HOST=etm
        networks:
            - elastest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers
volumes:
    edm-mysql:
      driver: local
networks:
    elastest:
      driver: bridge
