version: '3'
services:        
    etm-testlink:
      image: 'elastest/etm-testlink:1.0.0-beta1'
      depends_on:
            - edm-mysql
      expose:
            - 80
            - 443
      environment:
            - TESTLINK_USERNAME=none
            - TESTLINK_PASSWORD=none
            - MARIADB_HOST=edm-mysql
            - MARIADB_PASSWORD=
            - MARIADB_PORT_NUMBER=3306
            - MARIADB_USER=root
      networks:
             - elastest
      volumes:
             - etm-testlink:/bitnami
volumes:
    etm-testlink:
      driver: local
networks:
    elastest:
      driver: bridge
