version: '3'
services:
    etm:
        depends_on:
            - edm-mysql
            - etm-rabbitmq
            - edm-elasticsearch
            - etm-logstash
            - etm-beats
        links:
            - etm-rabbitmq
        container_name: elastest-etm
        image: elastest/etm
        environment:
            - EXEC_MODE=Normal
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
            - ET_EDM_MYSQL_HOST=edm-mysql
            - ET_EDM_MYSQL_PORT=3306
            - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:37003/
            - ET_EPM_API=http://epm:37002/
            - ET_ETM_API=http://etm:37006/
            - ET_ESM_API=http://esm:37005/
            - ET_EIM_API=http://eim:37004/
            - ET_ETM_LSBEATS_HOST=etm-beats
            - ET_ETM_LSBEATS_PORT=5044
            - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
            - ET_ETM_RABBIT_HOST=etm-rabbitmq
            - ET_ETM_RABBIT_PORT=5672
            - ET_ETM_INCONTAINER=true
            - ET_EMP_API=http://eim:37001/
            - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
            - ET_EMP_INFLUXDB_HOST=emp-influxdb
            - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
            - ET_ESM_SS_DESC_FILES_PATH=platform-services/
        entrypoint: /run.sh
        expose:
            - 8091
        ports:
            - 37006:8091
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - platform-services:/platform-services
        networks:
            - elastest
networks:
    elastest:
      driver: bridge
