version: '2.1'
services:
    etm-beats:
        container_name: beats
        image: elastest/etm-dockbeat
        environment:
            - LOGSTASHHOST=logstash
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - etm-logstash
        networks:
            - elastest
        
    etm-logstash:        
        container_name: logstash
        image: elastest/etm-logstash
        ports:
            - 5002:5002
            - 5000:5000
            - 5001:5001
            - 5044:5044
        depends_on:
            - etm-rabbitmq
            - edm-elasticsearch
        environment:
            - ELASTICHOST=edm-elasticsearch
            - RABBITHOST=etm-rabbitmq
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
                                  
    etm-rabbitmq:
        container_name: etm-rabbitmq
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        ports:
            - 15672:15672
            - 5672:5672
            - 15671:15671
            - 25672:25672
            - 61613:61613
        networks:
            - elastest

    etm:
        depends_on:
            - edm-mysql
            - etm-rabbitmq
            - edm-elasticsearch
            - etm-logstash
            - etm-beats
        links:
            - etm-rabbitmq
        container_name: elastest-etm
        image: elastest/etm
        environment:
            - EXEC_MODE=Normal
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19999/
            - ET_edm-mysql_HOST=edm-mysql
            - ET_edm-mysql_PORT=3306
            - ET_edm-elasticsearch_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:37003/
            - ET_EPM_API=http://epm:37002/
            - ET_ETM_API=http://etm:37006/
            - ET_ESM_API=http://esm:37005/
        entrypoint: /run.sh
        expose:
            - 8091
        ports:
            - 37006:8091
        volumes:
            - /test-results:/test-results
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - elastest
volumes:
    beats-data:
      driver: local
networks:
    elastest:
      driver: bridge
