version: '3'
services:
    etm-beats:
        container_name: beats
        image: elastest/etm-dockbeat
        environment:
            - LOGSTASHHOST=etm-logstash
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - etm-logstash
        networks:
            - elastest
        
    etm-logstash:        
        container_name: logstash
        image: elastest/etm-logstash
        ports:
            - 5002:5002
            - 5000:5000
            - 5001:5001
            - 5044:5044
        depends_on:
            - etm-rabbitmq
            - edm-elasticsearch
        environment:
            - ELASTICHOST=edm-elasticsearch
            - RABBITHOST=etm-rabbitmq
            - RABBITUSER=elastest-etm
            - RABBITPASS=elastest-etm
        networks:
            - elastest       
                                  
    etm-rabbitmq:
        container_name: etm-rabbitmq
        image: elastest/etm-rabbitmq
        hostname: my-rabbit
        ports:
            - 15672:15672
            - 5672:5672
            - 15671:15671
            - 25672:25672
            - 61613:61613
        networks:
            - elastest
volumes:
    beats-data:
      driver: local
networks:
    elastest:
      driver: bridge
