apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: platform-services
  name: platform-services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
