apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    elastest-component: ece
    io.elastest.service: ece
  name: ece
spec:
  ports:
  - name: "ece-8888"
    port: 8888
    targetPort: 8888
    nodePort: 37008
  selector:
    elastest-component: ece
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ece
  labels:
    elastest-component-type: te
    elastest-component: ece
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component-type: te
        elastest-component: ece
        io.elastest.service: ece
    spec:
      containers:
      - env:
        - name: ET_EMP_API
          value: http://emp:9100/v1/extension/elastest/tjobstat/
        - name: ET_EMP_APIKEY
          value: 480f410f-f506-4b7d-ac2b-dc51758d8d15
        - name: ET_EMP_SERIES
          value: docker-stats
        - name: ET_EMP_TOPIC
          value: user-1-elastest_core
        - name: ET_EMP_USER
          value: elastest
        - name: ET_ESM_API
          value: http://esm:37005/
        - name: ET_ETM_API
          value: http://etm:8091/
        image: elastest/ece:2.4.0
        imagePullPolicy: Always
        name: ece
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
