version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=elastest
      - POSTGRES_PASSWORD=elastestpassword
      - POSTGRES_DB=ece
  ece:
    image: elastest/ece:latest
    ports:
      - 37008:8888
    environment:
      - ET_ETM_API=http://etm:8091/
      - ET_ESM_API=http://esm:37005/
      - HIBERNATEURL=jdbc:postgresql://postgres/ece
      - ESTIMATIONRANGE=1,4,20,60