version: '3'

services:
  ece:
    image: elastest/ece:latest
    ports:
      - 37008:8888
    environment:
      - ET_ETM_API=http://etm:8091/
      - ET_ESM_API=http://esm:37005/
      - ET_EMP_API=http://emp:9100/v1/extension/elastest/tjobstat/
      - ET_EMP_APIKEY=480f410f-f506-4b7d-ac2b-dc51758d8d15
      - ET_EMP_USER=elastest
      - ET_EMP_TOPIC=user-1-elastest_core
      - ET_EMP_SERIES=docker-stats
    labels:
      - io.elastest.type=te