version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=elastest
      - POSTGRES_PASSWORD=elastestpassword
      - POSTGRES_DB=ece
  ece:
    image: elastest/ece:latest
    ports:
      - 37008:8888
    environment:
      - ELASTESTTORMAPI=http://etm:37006
      - ELASTESTESMAPI=http://esm:37005
      - ELASTESTTORMTJOBENDPOINT=/api/tjob
      - ELASTESTESMCATALOGENDPOINT=/v2/catalog
      - ELASTESTESMINSTANCEENDPOINT=/v2/et/service_instances/
      - HIBERNATEURL=jdbc:postgresql://postgres/ece
      - ESTIMATIONRANGE=1,4,20,60