apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.elastest: true
    io.elastest.service: eim
    elastest-component: eim
  name: eim
spec:
  ports:
  - name: "eim-8080"
    port: 8080
    targetPort: 8080
    nodePort: 37004
  selector:
    io.elastest.service: eim
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.elastest: true
    io.elastest.service: eim
    elastest-component-type: te
    elastest-component: eim
  name: eim
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        elastest-component-type: core
        elastest-component: eim
        io.elastest.service: eim
    spec:
      containers:
      - env:
        - name: ET_EDM_MYSQL_HOST
          value: edm-mysql
        - name: ET_EDM_MYSQL_PORT
          value: "3306"
        image: elastest/eim:latest
        name: eim
        ports:
        - containerPort: 8080
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
      imagePullPolicy: Always
status: {}
