version: '3'
services:
  eim:
    image: elastest/eim:2.3.0
    stdin_open: true
    tty: true
    environment:
      - ET_EDM_MYSQL_HOST=edm-mysql
      - ET_EDM_MYSQL_PORT=3306
    expose:
      - 8080
    ports:
      - "37004:8080" 
    labels:
      - io.elastest.type=core