apiVersion: v1
kind: Service
metadata:
  annotations:
    io.elastest: true
    io.elastest.service.type: te
  creationTimestamp: null
  labels:
    io.elastest: true
    io.elastest.service: ere
  name: ere-9080-service
spec:
  ports:
  - name: "ere-9080-host-port"
    port: 9080
    targetPort: 9080
    nodePort: 37008
  selector:
    io.elastest.service: ere
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: elastest-ere-data-claim
  labels:
    io.elastest: true
    io.elastest.pvc: elastest-ere-data-claim 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
status: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.elastest.type: te
  creationTimestamp: null
  labels:
    io.elastest: true
    io.elastest.service: ere
  name: ere
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.elastest.service: ere
    spec:
      containers:
      - image: 842800759158.dkr.ecr.eu-west-1.amazonaws.com/elastest/elastest-recommendation-engine:latest
        name: ere
        ports:
        - containerPort: 9080
        resources: {}
        volumeMounts:
        - mountPath: /ere-data
          name: ere-data
      restartPolicy: Always
      volumes:
      - name: ere-data
        persistentVolumeClaim:
          claimName: elastest-ere-data-claim
status: {}
