version: '3'

services:
  ere:
    image: 842800759158.dkr.ecr.eu-west-1.amazonaws.com/elastest/elastest-recommendation-engine:latest
    ports:
      - 37007:9080
      - 443:9443
    networks:
      - elastest
    volumes:
      - ~/ere-data:/ere-data:rw
    labels:
      - io.elastest.type=tss
      - io.elastest.tjob.tss.id=ere
      - io.elastest.tjob.tss.type=main
networks:
    elastest:
      driver: bridge