version: '3.4'
services:        
    etm-jenkins:
      image: 'elastest/etm-jenkins:1.0.0-beta5'
      expose:
            - 8080
      ports:
            - "37092:8080"
      environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            - INTEGRATED_JENKINS=true
      volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ${ET_DATA_IN_HOST}/jenkins_home:/var/jenkins_home