apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.elastest: true
    io.elastest.service: qa
    io.elastest.service.type: te
    elastest-component: qa
  name: qa
spec:
  ports:
  - name: "qa-9080-host-port"
    port: 9080
    targetPort: 9080
    notePort: 37009
  type: NodePort
  selector:
    elastest-component: qa
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: qa
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.elastest.type: te
        io.elastest: true
        io.elastest.service: qa
        io.elastest.service.type: te
        elastest-component.type: te
        elastest-component: qa
    spec:
      containers:
      - image: 842800759158.dkr.ecr.eu-west-1.amazonaws.com/elastest/elastest-qa-engine:latest
        name: qa
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
