version: '3'
services:
  qa:
    image: 842800759158.dkr.ecr.eu-west-1.amazonaws.com/elastest/elastest-qa-engine:latest
    ports:
      - 37009:9080
    expose:
      - 9443
    networks:
      - elastest
    volumes:
      - ${ET_DATA_IN_HOST}/eqe-data:/eqe-data:rw
    labels:
      - io.elastest.type=te
networks:
  elastest:
    driver: bridge