version: '3.4'
services:
  etm-testlink:
    image: elastest/etm-testlink:latest
    expose:
    - 80
    - 443
    environment:
      TESTLINK_USERNAME: admin
      TESTLINK_PASSWORD: elastest
      MARIADB_HOST: edm-mysql
      MARIADB_PASSWORD: null
      MARIADB_PORT_NUMBER: 3306
      MARIADB_USER: root
    volumes:
    - etm-testlink:/bitnami
volumes:
  etm-testlink:
# projectnametoreplace will be replaced to Elastest project name (elastest)
# the "name" property is available since compose 3.4 version
    name: projectnametoreplace_etm-testlink
    driver: local