version: '3.4'
services:
  etm-testlink:
    image: elastest/etm-testlink:latest
    expose:
    - 80
    - 443
    ports:
    - "37071:80"
    environment:
    - TESTLINK_USERNAME=none
    - TESTLINK_PASSWORD=none
    - MARIADB_HOST=edm-mysql
    - MARIADB_PASSWORD=null
    - MARIADB_PORT_NUMBER=3306
    - MARIADB_USER=root
    volumes:
    - etm-testlink:/bitnami
volumes:
  etm-testlink:
# projectnametoreplace will be replaced to Elastest project name (elastest)
# the "name" property is available since compose 3.4 version
    name: projectnametoreplace_etm-testlink
    driver: local