version: '3.4'
services:
  etm-testlink:
    image: elastest/etm-testlink:1.0.0
    expose:
    - 80
    - 443
    ports:
    - "37071:80"
    environment:
    - TESTLINK_USERNAME=none
    - TESTLINK_PASSWORD=none
    - MARIADB_HOST=edm-mysql
    - MARIADB_PASSWORD=
    - MARIADB_PORT_NUMBER=3306
    - MARIADB_USER=root
    volumes:
    - etm-testlink:/bitnami
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
volumes:
  etm-testlink:
# projectnametoreplace will be replaced to Elastest project name (elastest)
# the "name" property is available since compose 3.4 version
    name: projectnametoreplace_etm-testlink
    driver: local